### ISSUE TITLE
Error messages are always shown

### ISSUE THREAD

**Issue by alexnaish** [Financial-Times/o-forms#152]
When the form loads, the errortext messages are immediately shown even though there has been no interactions with the corresponding fields.

Should possibly be hidden until the input has been blurred and invalid?

Talked to @rowanmanning about this briefly, happy to discuss!

**Comment by rowanmanning** [comment]
OK I'm gonna outline what I _think_ the expected behaviour is, and then we can work from there. It's important that we cater for users who employ only server-side, or both server-side _and_ client-side validation.

Both of these assume that the error text is already in the DOM when the page loads.

## Server-Side

  * Field error text is included in the DOM regardless of whether there are errors or not. It is hidden by default, e.g.

    ```css
    .o-forms__errortext {
        display: none;
    }
    ```

  * When a field is in an error state, the server-side templates add an `o-forms--error` class to the field. This causes the error text to display, e.g.

    ```css
    .o-forms--error .o-forms__errortext {
        display: block;
    }
    ```

  * When a field is not in an error state, the error text will remain hidden, both visually and from screen-readers

## Client-Side

  * As with server-side, field error text is included in the DOM regardless of whether there are errors or not. It is hidden by default

  * When a field loses focus, the `o-forms--error` class is removed and client-side validation is run against the field value&hellip;

    * If the validation **passes**, nothing happens – `o-forms--error` is still not present and so the error text remains invisible

    * If the validation **fails**, the `o-forms--error` class is added to the field and the error text becomes visible (see CSS in server-side outline)

---

@alexnaish does this look sensible?

**Comment by alexnaish** [comment]
Thats exactly what I was thinking too, although within the client-side section there shouldn't be any classes added / removed until the blur event and the validation has completed.

**Comment by benbarnett** [comment]
Is it worth thinking about what happens on submit too? For visually impaired users, 'rolling' (`blur`) validation can easily be missed when tabbing through a form. Perhaps something like:

* When the form is submitted... 

  * If the validation **passes**, the submission carries on as normal
  * if the validation **fails**, an error summary is appended to the top of the form, and it is given focus to alert screen-reader users

Apologies if this is a separate issue!

**Comment by notlee** [comment]
This has been addressed in V5 of o-forms.
https://github.com/Financial-Times/o-forms/pull/147

Ben's suggestion for improved accessibility has been moved to this issue: https://github.com/Financial-Times/o-forms/issues/174
